In [7]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [8]:
df=pd.read_csv("../data/cpu_scheduling_process.csv")
df.head()

,process_id,arrival_time,burst_time,priority,process_type,short_job,long_job,io_flag,cpu_flag,high_priority,dynamic_arrival,best_algorithm
0,P1,16,4,4,IO-bound,1,0,1,0,0,1,SRTF
1,P2,4,16,1,CPU-bound,0,1,0,1,0,0,FCFS
2,P3,20,13,9,IO-bound,0,1,1,0,1,1,Priority
3,P4,14,19,2,IO-bound,0,1,1,0,0,1,Round Robin
4,P5,14,20,9,IO-bound,0,1,1,0,1,1,Priority

,process_id,arrival_time,burst_time,priority,process_type,short_job,long_job,io_flag,cpu_flag,high_priority,dynamic_arrival,best_algorithm
0,P1,16,4,4,IO-bound,1,0,1,0,0,1,SRTF
1,P2,4,16,1,CPU-bound,0,1,0,1,0,0,FCFS
2,P3,20,13,9,IO-bound,0,1,1,0,1,1,Priority
3,P4,14,19,2,IO-bound,0,1,1,0,0,1,Round Robin
4,P5,14,20,9,IO-bound,0,1,1,0,1,1,Priority